services:
  web:
    image: caddy:latest
    container_name: caddyweb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/public:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-net
    depends_on:
      - api

  api:
    build: ./backend/videofinder
    container_name: videoapi
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    networks:
      - app-net

networks:
  app-net:
    driver: bridge